sprint_2
ORLOVN/middle.messenger.praktikum.yandex pull request #2
Opened 2022-02-12 17:10 UTC by ORLOVN

2022-02-13 20:11 UTC, ivan-infro requested changes

2022-02-13 20:11 UTC, ivan-infro commented on src/pages/profile/profile.tmpl.ts
> +    {{#if editing}}<form class="profile-settings__settings-pane" method="post">{{else}}<div class="profile-settings__settings-pane">{{/if}}
В этом спринте необходимо выводить в консоль значение всех полей вместо отправки формы (сейчас срабатывает стандартное браузерное поведение - POST (т.к. method="post") запрос на ту же страницу)
<img width="576" alt="image" src="https://user-images.githubusercontent.com/5419627/153772459-aeae2687-0bb8-476b-b6fa-9f99d42f294c.png">

2022-02-13 20:11 UTC, ivan-infro commented on package.json
> +    "lint": "eslint . --ext .ts"
Проект должен успешно проходить проверку линтером
<img width="882" alt="image" src="https://user-images.githubusercontent.com/5419627/153772345-6d08faf3-7f55-405f-b635-046c4c599860.png">

2022-02-13 20:11 UTC, ivan-infro commented on README.md
> +Приложение выполнено по заданию Yandex practicum (sprint no 2)\
Необходимо убедиться, что все автотатические тесты 2го спринта проходят успешно (сейчас падает тест на роутинг)

Error: Routing problem
[5](https://github.com/ORLOVN/middle.messenger.praktikum.yandex/runs/5168661686?check_suite_focus=true#step:10:5)

2022-02-13 20:11 UTC, ivan-infro commented on src/index.css
> +.ref-pane a{
Старайтесь избегать селекторов по тегу (a), это снижает переиспользуемость кода

2022-02-13 20:11 UTC, ivan-infro commented on src/index.html
>      <link rel="preconnect" href="https://fonts.googleapis.com">
FYI (не требует исправления): Использование Google Fonts несовместимо с GDPR :( 
https://thehackernews.com/2022/01/german-court-rules-websites-embedding.html

2022-02-13 20:11 UTC, ivan-infro commented on src/index.ts
> +    block.dispatchComponentDidMount();
componentDidMount должен вызываться прозрачно для "пользователя" (разработчика)
Текущая схема с ручным вызовом `dispatchComponentDidMount` приведет к большому дублированию кода и неконсистетным порядком вызова данного события

2022-02-13 20:11 UTC, ivan-infro commented on src/pages/profile/profile.ts
> +                    click: (event) =>{
Лучше использовать кнопку type="submit" вместо ручного вызова submit у формы, это повысит a11y (accessibility) страницы

2022-02-14 08:16 UTC, ORLOVN commented
Закрыл этот пул реквест, так как тесты не подхватывали новые коммиты.

2022-02-15 16:29 UTC, ivan-infro commented on src/components/button/button.ts
> +        content?: string,
Описание тип Props лучше выносить отдельно:

`type ButtonProps = { ... } 
export class Button extends Block {
     constructor(props: ButtonProps)
`

2022-02-15 16:31 UTC, ivan-infro commented on src/index.css
> +  -webkit-font-smoothing: antialiased;
FYI: Префиксы можно автоматически добавлять на этапе сборке.
В следующих спринтах вы будете настраивать сборку с помощью webpack, там можно будет применить, например, https://github.com/postcss/autoprefixer

2022-02-15 16:33 UTC, ivan-infro approved these changes

2022-02-17 09:43 UTC, merged